#!/bin/sh

# Creates resources.toit from the image files in this directory.

# Requires Posix tools like hexdump, tr, and sed.

# Exit on errors.
set -e

# Correct behaviour if there is no match for some of the file suffixes.
shopt -s nullglob

cat resources.toit.header > resources.toit

# Binary files are turned into ByteArrays.
for filename in *.{png,PNG,jpg,JPG,jpeg,JPEG}
do
    echo                                                                   >> resources.toit
    echo "/// Autogenerated from $filename."                               >> resources.toit
    echo -n $filename | sed 's/\.[a-z]\+$//' | tr a-z- A-Z_                >> resources.toit
    echo " ::= #["                                                         >> resources.toit
    hexdump -ve '"  " 12/1 "0x%02x, " "\n"' $filename | sed 's/, 0x  //g'  >> resources.toit
    echo "]"                                                               >> resources.toit
done

# Text files are turned into strings.
for filename in *.{css,html,svg}
do
    echo                                                                   >> resources.toit
    echo "/// Autogenerated from $filename."                               >> resources.toit
    echo -n $filename | sed 's/\.[a-z]\+$//' | tr a-z- A-Z_                >> resources.toit
    echo ' ::= """'                                                        >> resources.toit
    sed 's/\r//g' $filename                                                >> resources.toit
    echo '"""'                                                             >> resources.toit
done


echo ""                                                                   >> resources.toit
echo "RESOURCE_MAP ::= {"                                                 >> resources.toit
for filename in *.{png,PNG,jpg,JPG,jpeg,JPEG,css,html,svg}
do
    echo -n "  \"$filename\": " | sed 's/\.[a-z]\+$//'                    >> resources.toit
    echo "$filename" | sed 's/\.[a-z]\+$/,/' | tr a-z- A-Z_               >> resources.toit
done
echo "}"                                                                  >> resources.toit
